UST-QuAntiL/qc-atlas

docs/dev/config/IntelliJ IDEA/README.md
Mac commands added, small fixes for the structure
=> add mac commands and small adjustments

org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/dtos/entities/AlgorithmDto.java, org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/dtos/entities/AlgorithmListDto.java, org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/dtos/entities/ImplementationDto.java, org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/dtos/entities/ImplementationListDto.java, org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/dtos/entities/ParameterDto.java, org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/dtos/entities/ParameterListDto.java, org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/dtos/entities/ProviderDto.java, org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/dtos/entities/ProviderListDto.java, org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/dtos/entities/QpuDto.java, org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/dtos/entities/QpuListDto.java, org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/dtos/entities/SdkDto.java, org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/dtos/entities/SdkListDto.java, org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/dtos/entities/TagDto.java, org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/dtos/requests/CreateQpuRequest.java, org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/dtos/requests/ParameterKeyValueDto.java, org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/dtos/requests/SelectionParameterDto.java, org.planqk.atlas.core/org.planqk.atlas.core.model/src/main/java/org/planqk/atlas/core/model/AlgorOrImpl.java, org.planqk.atlas.core/org.planqk.atlas.core.model/src/main/java/org/planqk/atlas/core/model/Algorithm.java, org.planqk.atlas.core/org.planqk.atlas.core.model/src/main/java/org/planqk/atlas/core/model/HasId.java, org.planqk.atlas.core/org.planqk.atlas.core.model/src/main/java/org/planqk/atlas/core/model/Implementation.java, org.planqk.atlas.core/org.planqk.atlas.core.model/src/main/java/org/planqk/atlas/core/model/Parameter.java, org.planqk.atlas.core/org.planqk.atlas.core.model/src/main/java/org/planqk/atlas/core/model/Provider.java, org.planqk.atlas.core/org.planqk.atlas.core.model/src/main/java/org/planqk/atlas/core/model/Qpu.java, org.planqk.atlas.core/org.planqk.atlas.core.model/src/main/java/org/planqk/atlas/core/model/Sdk.java, org.planqk.atlas.core/org.planqk.atlas.core.model/src/main/java/org/planqk/atlas/core/model/Tag.java, pom.xml
Use lombock to generate Getters, Setters, and ToString methods for the data objects.
* Add lombock dependency
* Format POM to code style
* Add lombock annotations to data classes and remove implemented methods
=> Use lombock to generate Getter and Setter for data objects

org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/controller/AlgorithmController.java, org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/controller/ImplementationController.java, org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/dtos/entities/AlgorithmDto.java, org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/dtos/entities/ImplementationDto.java, org.planqk.atlas.core/org.planqk.atlas.core.model/src/main/java/org/planqk/atlas/core/model/AlgorOrImpl.java, org.planqk.atlas.nisq.analyzer/org.planqk.atlas.nisq.analyzer.control/src/main/java/org/planqk/atlas/nisq/analyzer/control/NisqAnalyzerControlService.java
delete width and depth formula as it will be replaced by transpiler results later
=> delete width and depth formula

README.md, org.planqk.atlas.war/pom.xml, org.planqk.atlas.war/src/main/resources/application.properties, pom.xml
=> add persistent postgres db

org.planqk.atlas.api/src/main/java/org/planqk/atlas/api/dtos/entities/ImplementationDto.java
Add implementation input and output parameter handling for database
=> Fix parameter handling for implementions

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ProviderController.java, org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/AlgorithmControllerTest.java, org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/ProviderControllerTest.java
Add tests for the provider controller.
=> Add tests for the provider controller

.travis.yml, Dockerfile, pom.xml
update from java 8 to java 11 as this is the latest version of java that offers long term support (LTS)
* change java version
* change java version in dockerfile
=> update to the latest version of java that offers long term support (LTS)

org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/AlgorOrImpl.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/Implementation.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/TagController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/AlgorithmDto.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/ImplementationDto.java
Some DTOs and Model classes were inconsistent with the specified data model. This had to be fixed in order to generate all services in the frontend which were previously written by hand.
=> Model Harmonization for OpenAPI integration

org.planqk.atlas.web/pom.xml, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/Application.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ImplementationController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ProviderController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/QpuController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/RootController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/TagController.java, org.planqk.atlas.web/src/main/resources/application.properties, pom.xml
Adds OpenAPI annotations to support auto generation for client stubs
[Issue](https://github.com/PlanQK/q-tal/issues/29)
=> Adds OpenAPI support

org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/Backend.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/CloudService.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/SoftwarePlatform.java
Added model classes for SoftwarePlatform, CloudService and Backend in order to reduce dependencies in continuous software development process.
=> Added model classes for SoftwarePlatform, CloudService and Backend

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/AlgorithmDto.java
Adds missing fields to AlgorithmDto
=> Adds missing fields to AlgorithmDto

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgoRelationTypeController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ImplementationController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ProblemTypeController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ProviderController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/QpuController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/RootController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/TagController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/ImplementationDto.java
Adds missing OpenAPI annotations in controller classes
=> Fix OpenAPI annotations in controller classes

.travis.yml, pom.xml
Since codecov seems to fail, this pr will attempt to fix it.
=> Fix Codecov

org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/Algorithm.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/AlgorithmRelation.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/ClassicAlgorithm.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/ClassicImplementation.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/Implementation.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/QuantumAlgorithm.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/QuantumImplementation.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/Tag.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ImplementationService.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ImplementationController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/ImplementationDto.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/linkassembler/ImplementationAssembler.java, org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/AlgorithmControllerTest.java, org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/ImplementationControllerTest.java
Adds QuantumImplementation and ClassicImplementation types
=> QuantumImplementation and ClassicImplementation types

org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/Algorithm.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/PatternRelation.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/PatternRelationType.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/repository/PatternRelationRepository.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/repository/PatternRelationTypeRepository.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/PatternRelationService.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/PatternRelationServiceImpl.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/PatternRelationTypeService.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/PatternRelationTypeServiceImpl.java, org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/PatternRelationServiceTest.java, org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/PatternRelationTypeServiceTest.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/Constants.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/PatternRelationController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/PatternRelationTypeController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/RestErrorHandler.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/PatternRelationDto.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/PatternRelationTypeDto.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/linkassembler/AlgorithmAssembler.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/linkassembler/PatternRelationAssembler.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/linkassembler/PatternRelationTypeAssembler.java, org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/AlgorithmControllerTest.java, org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/PatternRelationControllerTest.java, org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/PatternRelationTypeControllerTest.java
Adds PatternRelation and PatternRelationType with a complete CRUD-Interface to implement issue https://github.com/PlanQK/q-tal/issues/11
=> Add Pattern Relations and Pattern Relation Types

org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/Implementation.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ImplementationService.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ImplementationServiceImpl.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ImplementationController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/ImplementationDto.java, org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/ImplementationControllerTest.java
Adds publications to implementations and fixes implementation service
* Add publications to implementations
**Fixes**: 
* Implementation service
=> Adds publications to implementations and fixes implementation service

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/CloudServiceController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/SoftwarePlatformController.java, org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/CloudServiceControllerTest.java, org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/SoftwarePlatformControllerTest.java
Fixed controller mappings for software platform and cloud service
* Changed PUT mapping of add functions in to POST mappings
=> Fixed controller mappings for software platform and cloud service

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/AlgorithmDto.java
Fixed size constaint in algorithmDto
=> Fixed size constaint in algorithmDto

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/exceptions/InvalidTypeException.java
=> Add missing error message for QuantumResource mappings

.travis.yml, docs/dev/running-db-tests.md, org.planqk.atlas.core/src/test/resources/db-test.properties
* Changes the database for tests from `planqk` to `planqk_test`
* Adds shord document to describe how the database is created.
=> Change database for tests

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/AlgorithmDto.java
* improve swagger annotions (still not perfect for algorithms-relations, but better)
=> improve swagger annotations for algorithmDTO

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ImplementationController.java
* I started extending the swagger documentation
=> add documentation

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/PublicationController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/linkassembler/PublicationAssembler.java
Temporarily remove Get on publications to retrieve related algorithms
=> Remove link from publications to related algorithms

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java
* delete PUT on problemTypes list
* add GET/DELETE for references of problemtypes for an algorithm
=> adjust methods for problemtypes of an algorithm

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/AlgorithmDto.java
* should be analogous to problemtype
=> applicationAreas should not be set in a post on /algorithms/ and is not a list of strings anymore

org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/Implementation.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/QuantumImplementation.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/SoftwarePlatform.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ImplementationController.java, org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/ImplementationControllerTest.java
Add routes to handle software platform references behind implementations of algorithms
=> Add route for software platforms behind implementations

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/linkassembler/AlgoRelationTypeAssembler.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/linkassembler/AlgorithmAssembler.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/linkassembler/ApplicationAreaAssembler.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/linkassembler/BackendAssembler.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/linkassembler/CloudServiceAssembler.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/linkassembler/ComputingResourceAssembler.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/linkassembler/DiscussionCommentAssembler.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/linkassembler/DiscussionTopicAssembler.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/linkassembler/PatternRelationTypeAssembler.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/linkassembler/ProblemTypeAssembler.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/linkassembler/PublicationAssembler.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/linkassembler/QuantumResourceTypeAssembler.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/linkassembler/SoftwarePlatformAssembler.java
* delete "update" "delete" links in all assemblers
=> delete update delete links

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgoRelationTypeController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ApplicationAreaController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ComputingResourceTypeController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ImplementationController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/PatternRelationController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/PatternRelationTypeController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ProblemTypeController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/PublicationController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/SoftwarePlatformController.java
* add swagger documentation for put and post requests
=> add swagger documentation for put and post

.travis.yml
=> Fix Travis to use OpenJDK instead of OracleJDK

org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/repository/AlgorithmRepository.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/AlgorithmService.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/AlgorithmServiceImpl.java, org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/AlgorithmServiceTest.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/RootController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/utils/RestUtils.java, org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/AlgorithmControllerTest.java
Fronend Algorithm List view requires new QueryParameters.
- Added Sorting to Utils and implemented them within the "/algorithm" endpoint
- Added Search to "/algorithm" endpoint, allowing search of certain algorithm attributes
=> Feature add optional algorithm query params

org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/DiscussionTopic.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/KnowledgeArtifact.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/repository/DiscussionCommentRepository.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/repository/DiscussionTopicRepository.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/DiscussionTopicService.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/DiscussionTopicServiceImpl.java, org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/DiscussionCommentServiceTest.java, org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/DiscussionTopicServiceTest.java, org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/PublicationServiceTest.java
=> Fix DiscussionTopic relationship with KnowledgeArtifact 

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/SwaggerConfiguration.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/ClassicImplementationDto.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/QuantumAlgorithmDto.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/QuantumImplementationDto.java
Currently some DTOs use Entity models instead of existing DTO-Models
Replace Entites with DTOs in mentioned DTO objects
=> Swapped remaining Entities with DTOs in DTO-Objects

org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/Implementation.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ImplementationServiceImpl.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/ImplementationDto.java
extend Implementation entity and DTO
extend Implementation entity and DTO with
* problemStatement
* version
* license
=> extend Implementation entity and DTO

README.md
- Fix Travis badge in the README
- Update the Git Flow workflow link to the english version.
Resolves #132
=> Fix Travis badge in the README

docs/dev/running-db-tests.md
Replaces the outdated instructions to run service tests with the more recent ones.
Resolves UST-QuAntiL/q-tal#101
=> Update Database Tests Documentation

README.md
Adds the Codecov badge, to quickly access the codecov page of this repo.
=> Add Codecov Badge

.docker/application.properties.tpl, org.planqk.atlas.web/src/main/resources/application.properties
The proposed changes fix the initialization mode of the db which previously prevented the usage of already existing data/schemes
=> Fix db init mode

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ImplementationGlobalController.java, org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/ImplementationGlobalControllerTest.java
add getImplementation() in ImplementationGlobalController.java
* add getImplementation() in ImplementationGlobalController.java
* Tests
*
=> add getImplementation() in ImplementationGlobalController.java

docs/adr/0003-model-mapper.md, docs/adr/0004-postgres-for-service-tests.md, docs/adr/0005-use-OpenAPI.md, docs/adr/0006-model-assemblers.md, docs/adr/0007-junit-for-testing.md, docs/adr/0008-testcontainers.md, docs/adr/index.md
=> Add Architectural Decision Records

org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/Implementation.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ImplementationServiceImpl.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/ImplementationDto.java
add technology to entity and DTO
* add technology to entity and DTO
* add text annotation for implementation.description
=> feat(PLANQK-179): add technology attribute

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/ImplementationDto.java
Add softwarePlatforms to ImplementationDto
* Add softwarePlatforms to ImplementationDto
=> add softwarePlatforms to ImplementationDto.java

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java, org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/AlgorithmControllerTest.java
Add missing pagination to controller functions
* getImplementationsOfAlgorithm
=> Add missing pagination to controller functions

.github/workflows/build_swagger_ui.yml
Automatically publishes the OpenAPI docs to GitHub Pages
=> Publish API docs to GitHub Pages using GitHub Actions

.docker/application.properties.tpl, .gitignore, org.planqk.atlas.core/pom.xml, org.planqk.atlas.core/src/main/resources/db/changelog-master.xml, org.planqk.atlas.core/src/main/resources/db/changelog/2020-10-14-00-00-initial.xml, org.planqk.atlas.web/pom.xml, org.planqk.atlas.web/src/main/resources/application.properties, pom.xml
**Fixes**:  UST-QuAntiL/q-tal#75
=> Database migrations

org.planqk.atlas.web/pom.xml
execute classifier with jar profile
=> execute classifier with jar profile

org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/SketchServiceImpl.java
=> fix(#19): save sketches in base64

org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/Sketch.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/SketchServiceImpl.java, org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/SketchServiceTest.java, org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/AlgorithmControllerTest.java
Set sketch imageURL as String because we might want to use the relative path
=> fix(#11): set sketch imageURL as String

org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ProblemTypeServiceImpl.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/util/Constants.java
Sort List of Problem Types by Parent Problem Type Name. Getting 500 error on sort request.
Added logic to sort based Parent Problem Type Name. Parent Problem Type is a UUID type field, so first we have to fetch corresponding names using the UUIDs and then sort.
*
*
*
**Fixes**: #
=> 134 bug sort

org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/ComputeResource.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/ComputeResourceDto.java
Add a flag to computeResourceDto and entity to show the source of qpu (user or from qprov)
=> adding the source of qpu

org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/ProblemTypeServiceTest.java, org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/AlgorithmControllerTest.java, org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/LearningMethodControllerTest.java
Added a few new test cases for services and controllers
=> New test cases

config/default-config.json, docker-compose.yml, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/Implementation.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/repository/ImplementationRepository.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ImplementationService.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ImplementationServiceImpl.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/Constants.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ImplementationGlobalController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/ImplementationDto.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/PatternUriDto.java
Adds the functionality to link implementations with patterns from the Pattern Atlas.
Related issue: https://github.com/UST-QuAntiL/qc-atlas/issues/217
=> Add patterns to implementations

org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/FileData.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/repository/FileDataRepository.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/FileServiceImpl.java, org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/FileServiceTest.java
Store files of ImplementationPackages in the existing PostgreSQL DB.
=> Feature: Store Files in existing DB

.github/workflows/dockerhub.yml
Fix the DockerHub action to ensure the GitHub release correctly pushes the Docker image.
=> Fix dockerhub action

org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/Implementation.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/repository/ImplementationRepository.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ImplementationService.java, org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ImplementationServiceImpl.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ImplementationGlobalController.java, org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/PatternUriDto.java
Store patterns of an implementation as strings.
=> Store patterns as string
