.docker/application.properties.tpl
Dockerfile

Add a template with application.properties that is used by the dockerized QC-Atlas and adapt Dockerfile correspondingly.

Add template for configuration and use it on docker startup

---

.travis.yml
codecov.yml
org.planqk.atlas.core/pom.xml
org.planqk.atlas.web/pom.xml
pom.xml

Add Coverage support for Maven to the whole Project
- Add Jacoco plugin to Maven
- Autmaticcaly generated HTML reports and the report mandatory for codecov when running `mvn package`
- Adds configuration for codecov
- Adds codecov to travis.yml

Add Coverage Support for pom.xml

---

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/Application.java
org.planqk.atlas.web/src/main/resources/application.properties

This adds a `main`-method to the `Application` class so that developers can use Spring Boot's embedded Tomcat server instead of having to set one up.
Also, set the correct context-path for the embedded tomcat server.

Add main method to Application class

---

org.planqk.atlas.web/src/main/resources/application.properties

These properties are only relevant for non-docker setups, in which case
you'd want more descriptive db / user names.
**Fixes**: PlanQK/q-tal#21

Change default PostgreSQL user and database name

---

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/SpringOverrides.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/annotation/ApiVersion.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/annotation/VersionedRequestHandlerMapping.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ImplementationController.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ProviderController.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/QpuController.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/TagController.java
org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/annotation/VersionedRequestHandlerMappingTest.java
org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/ImplementationControllerTest.java

This PR adds API versioning on the controller level. Versions are appended to the controller's path prefix.
This however means that controllers with nested namespaces are not supported. The two affected controllers had their paths changed.
**Fixes**: PlanQK/q-tal#8

Add API versioning on controller-level

---

.dockerignore

With inconsitent dependencies the Docker image may not work properly, this PR therefore adds a dockerignore to prevent such issues.
* Add a `.dockerignore` file to all files Docker does not need in order to build the Image.

Add a Dockerignore to prevent dependency issues

---

docs/dev/OpenAPI.md

Adds documentation for OpenAPI which briefly explains what the specification is about and how to generate client stubs.

Documentation for OpenAPI

---

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/SpringOverrides.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/utils/EntityModelConverter.java
org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/utils/EntityModelConverterTest.java

The EntityModel class wraps our DTOs, but due to a (maybe deliberate?) choice,
Swagger ignores constraints on @JsonWrapped-imported properties.
This means we lose our required properties, min/max values, and so on, which is unacceptable.

Fix OpenAPI schema constraints for EntityModel<T> wrappers

---

org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/util/AtlasDatabaseTestBase.java

This annotation is added ensure every test uses an empty database.

Add 'DirtiesContext' annotation to the base service test

---

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/AlgorithmDto.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/QuantumAlgorithmDto.java

Last PR introduced possiblity for NullPointerExceptions since we removed the Null-Check-Getter methods in Algorithm because all Sets are initialized but we forgot to do the same in the AlgorithmDTO. This leads to the ModelMapper mapping Null-Sets to our Algorithm which are not checked anymore.
**Fixes**: 
- Sets in AlgorithmDTO are initialized

Init AlgoDto sets to avoid NullPointer

---

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/SwaggerConfiguration.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/utils/LinkRemoverModelConverter.java

Removes the `_links` property from the spec of all `RepresentationModel` sub-types.
This is realized via a custom `ModelConverter` that can be enabled or disabled as-needed.

Remove `_links` from our OpenAPI spec for now

---

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/SwaggerConfiguration.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/AlgorithmDto.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/ClassicAlgorithmDto.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/QuantumAlgorithmDto.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/utils/EntityModelConverter.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/utils/OverrideModelConverter.java
org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/utils/EntityModelConverterTest.java
org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/utils/OverrideModelConverterTest.java

This allows us to have simple custom schema objects for polymorphic types.
Unfortunately, simply setting `oneOf = ...` on the parent class of one of our
polymorphic DTOs doesn't work, as the resulting type spec contains reference cycles
or mixes property lists with union types (which isn't supported by code generators).
**Fixes**: PlanQK/q-tal#48

Improve Swagger spec for polymorphic types

---

.travis.yml
org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/DiscussionCommentControllerTest.java
org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/DiscussionTopicControllerTest.java

Replaces Test Annotations (`@SpringBootTest` with `@WebMvcTest`) of the `DiscussionTopicControllerTest` and `DiscussionCommentControllerTest` to remove the database requirement.

Remove Database dependency for Controller Tests

---

org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/Implementation.java

The automatically generated definition is incorrect:
```sql
CREATE TABLE public.implementation_publications
(
implementation_id uuid NOT NULL,
publications_id uuid NOT NULL,
implementations_id uuid NOT NULL,
...
```

Fix table definition for implementation <> publication relations

---

org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/AlgorithmServiceImpl.java

Currently when an Algorithm is updated via the PUT endpoint, it sets attributes that are not part of the dto. Those attributes will therefor be removed from the algorithm, even though it was not the intention
- Commented out update of algorithm attributes that are updated over other endpoints (Tag, ProblemType, etc.)

Fixed Update Algorithm

---

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/CorsConfiguration.java

Configure CORS using the WebMvcConfigurer
* Use WebMvcConfigurer to globally allow Cross Origin Requests. To disable it, just uncomment the Configuration annotation

Configure Cross Origin (CORS) globally

---

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/WebConfiguration.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/RootController.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/utils/ListParameters.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/utils/ListParametersDoc.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/utils/ListParametersMethodArgumentResolver.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/utils/RestUtils.java

To make things more robust, keep common list parameters in a dedicated class.
This way, the parameter documentation, parsing logic and so on stays the same.
Also, the amount of boilerplate code in the controllers is further reduced.

Add custom argument type for data-list parameters

---

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/AlgorithmController.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/ImplementationController.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/controller/PatternRelationController.java

Previously duplicate operationIds generated from OpenAPI received a `_[0-9]+` suffix. 
This PR fixes that by giving duplicate operationIds meaningful names.
Resolves [Issue #58](https://github.com/PlanQK/q-tal/issues/58) for the backend.

Changes duplicate operationIds to meaningful names

---

README.md
org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/AlgorithmServiceImpl.java
org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ComputeResourcePropertyServiceImpl.java
org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ProblemTypeService.java
org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ProblemTypeServiceImpl.java
org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/PublicationServiceImpl.java
org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/SketchServiceImpl.java
org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/SoftwarePlatformServiceImpl.java
org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/util/ServiceUtils.java
org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/AlgorithmRelationServiceTest.java
org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/AlgorithmServiceTest.java
org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/ApplicationAreaServiceTest.java
org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/ComputeResourcePropertyServiceTest.java
org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/ComputeResourcePropertyTypeServiceTest.java
org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/ImplementationServiceTest.java
org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/PatternRelationServiceTest.java
org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/ProblemTypeServiceTest.java
org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/PublicationServiceTest.java
org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/SketchServiceTest.java
org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/SoftwarePlatformServiceTest.java
org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/AlgorithmControllerTest.java

Add missing service tests for new service methods created by the refactoring that were not added in the refactoring PR
* Add missing service tests for AlgorithmRelationService
* Add missing service tests for AlgorithmService
* Add missing service tests for ComputeResourcePropertyService
* Add missing service tests for ImplementationService
* Add missing service tests for PatternRelationService
* Add missing service tests for PublicationService
* Add missing service tests for SoftwarePlatformService
* Adjusted multiple service tests in order to fully test functionality

Add missing service tests

---

org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/AlgorithmServiceImpl.java
org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ApplicationAreaServiceImpl.java
org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/CloudServiceServiceImpl.java
org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ComputeResourceServiceImpl.java
org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ImplementationServiceImpl.java
org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/PublicationServiceImpl.java
org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/SoftwarePlatformServiceImpl.java
org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/util/CollectionUtils.java

Custom removal methods such as `removeAlgorithm()` try to remove an element from both sides of its relationship.
This randomly fails as we're iterating over one of the two containers involved.
**Fixes**: #148

Fix ConcurrentModificationException when deleting entities

---

org.planqk.atlas.core/src/main/resources/db/changelog-master.xml

It appears the 'executable jar/war' built via the Spring Boot maven plugin
doesn't support directory listings for classpath URIs, breaking the automatic
OpenAPI spec extraction.

Include all DB migration changelogs manually

---

docker-compose.yml
org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/model/AlgorithmRelationType.java
org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/AlgorithmRelationTypeServiceImpl.java
org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/AlgorithmRelationServiceTest.java
org.planqk.atlas.core/src/test/java/org/planqk/atlas/core/services/AlgorithmRelationTypeServiceTest.java
org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/AlgorithmRelationTypeDto.java
pom.xml

Add inverseTypeName to AlgorithmRelationTypes.
Additionally, fix db ports to 5060.
Tackles https://github.com/UST-QuAntiL/qc-atlas/issues/188

define inverseTypeName and adapt port for db

---

org.planqk.atlas.web/src/main/java/org/planqk/atlas/web/dtos/AlgorithmRelationDto.java
org.planqk.atlas.web/src/test/java/org/planqk/atlas/web/controller/AlgorithmRelationControllerTest.java

To be uniform with the platform, renaming of algoRelationType to algorithmRelationType.

rename algoRelationType to algorithmRelationType

---

.docker/application.properties.tpl

Use 150 MB as a default value for `spring.servlet.multipart.max-file-size`  and `spring.servlet.multipart.max-request-size` in the Docker container.
Signed-off-by: Marvin Bechtold <marvin.bechtold.dev@gmail.com>

Add default values for multipart config to Docker container

---

org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/FileServiceImpl.java
org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/ImplementationPackageServiceImpl.java
org.planqk.atlas.core/src/main/java/org/planqk/atlas/core/services/SolutionServiceImpl.java

Fixes:
- each uploaded file had to have a unique file name when using the database as file store
- error handling when a solution already has a file

Fix unique file name constraint
